// registry/tis/badge.tsx
import * as React from "react"

import { cn } from "./tis-utils"

type BadgeTone = "brand" | "success" | "warning" | "error" | "info" | "neutral"
type BadgeVariant = "solid" | "subtle"

type BadgeProps = React.ComponentProps<"span"> & {
  tone?: BadgeTone
  variant?: BadgeVariant
}

function Badge({
  className,
  tone = "brand",
  variant = "solid",
  ...props
}: BadgeProps) {
  return (
    <span
      data-slot="badge"
      data-tone={tone}
      data-variant={variant}
      className={cn(
        "ds-badge",
        `ds-badge--${tone}`,
        `ds-badge--${variant}`,
        className,
      )}
      {...props}
    />
  )
}

export { Badge, type BadgeProps, type BadgeTone, type BadgeVariant }

// packages/angular/badge/src/badge.ts
import {
  ChangeDetectionStrategy,
  Component,
  input,
} from "@angular/core";

export type TisBadgeTone =
  | "brand"
  | "error"
  | "info"
  | "neutral"
  | "success"
  | "warning";
export type TisBadgeVariant = "solid" | "subtle";

@Component({
  selector: "tis-badge",
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: {
    class: "ds-badge",
    "data-tis-angular-badge": "",
    "[attr.data-tone]": "tone()",
    "[attr.data-variant]": "variant()",
    "[class.ds-badge--brand]": "tone() === 'brand'",
    "[class.ds-badge--error]": "tone() === 'error'",
    "[class.ds-badge--info]": "tone() === 'info'",
    "[class.ds-badge--neutral]": "tone() === 'neutral'",
    "[class.ds-badge--success]": "tone() === 'success'",
    "[class.ds-badge--warning]": "tone() === 'warning'",
    "[class.ds-badge--solid]": "variant() === 'solid'",
    "[class.ds-badge--subtle]": "variant() === 'subtle'",
  },
  template: `<ng-content />`,
})
export class TisBadge {
  readonly tone = input<TisBadgeTone>("brand");
  readonly variant = input<TisBadgeVariant>("solid");
}
