// registry/tis/spinner.tsx
import * as React from "react"

import { cn } from "./tis-utils"

type SpinnerSize = "sm" | "md" | "lg"

type SpinnerProps = React.ComponentProps<"span"> & {
  onColor?: boolean
  size?: SpinnerSize
}

function Spinner({
  className,
  onColor = false,
  size = "md",
  role = "status",
  "aria-label": ariaLabel = "Loading",
  ...props
}: SpinnerProps) {
  return (
    <span
      data-slot="spinner"
      data-size={size}
      data-on-color={onColor || undefined}
      role={role}
      aria-label={ariaLabel}
      className={cn(
        "ds-spinner",
        `ds-spinner--${size}`,
        onColor && "ds-spinner--on-color",
        className,
      )}
      {...props}
    />
  )
}

export { Spinner, type SpinnerProps, type SpinnerSize }

// packages/angular/spinner/src/spinner.ts
import { ChangeDetectionStrategy, Component, booleanAttribute, input } from "@angular/core";

export type TisSpinnerSize = "sm" | "md" | "lg";

@Component({
  selector: "tis-spinner",
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: {
    style: "display: contents",
  },
  template: `<span
    class="ds-spinner"
    data-tis-angular-spinner
    [attr.data-size]="size()"
    [attr.data-on-color]="onColor() ? '' : null"
    [class.ds-spinner--sm]="size() === 'sm'"
    [class.ds-spinner--md]="size() === 'md'"
    [class.ds-spinner--lg]="size() === 'lg'"
    [class.ds-spinner--on-color]="onColor()"
    [attr.role]="decorative() ? null : 'status'"
    [attr.aria-label]="decorative() ? null : label()"
    [attr.aria-hidden]="decorative() ? 'true' : null"
  ></span>`,
})
export class TisSpinner {
  readonly size = input<TisSpinnerSize>("md");
  readonly onColor = input(false, { transform: booleanAttribute });
  readonly decorative = input(false, { transform: booleanAttribute });
  readonly label = input("Carregando");
}
