// packages/angular/alert/src/alert.ts
import {
  ChangeDetectionStrategy,
  Component,
  Directive,
  computed,
  input,
} from "@angular/core";

export type TisAlertTone = "error" | "info" | "success" | "warning";
export type TisAlertVariant = "solid" | "subtle";
export type TisAlertRole = "alert" | "status";

@Component({
  selector: "tis-alert",
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: {
    class: "ds-alert",
    "data-tis-angular-alert": "",
    "[attr.data-tone]": "tone()",
    "[attr.data-variant]": "variant()",
    "[attr.role]": "effectiveRole()",
    "[class.ds-alert--error]": "tone() === 'error'",
    "[class.ds-alert--info]": "tone() === 'info'",
    "[class.ds-alert--success]": "tone() === 'success'",
    "[class.ds-alert--warning]": "tone() === 'warning'",
    "[class.ds-alert--solid]": "variant() === 'solid'",
    "[class.ds-alert--subtle]": "variant() === 'subtle'",
  },
  template: `<ng-content />`,
})
export class TisAlert {
  readonly tone = input<TisAlertTone>("info");
  readonly variant = input<TisAlertVariant>("subtle");
  readonly role = input<TisAlertRole | null>(null);
  protected readonly effectiveRole = computed<TisAlertRole>(() =>
    this.role() ?? (this.tone() === "error" ? "alert" : "status"),
  );
}

@Directive({
  selector: "[tisAlertIcon]",
  standalone: true,
  host: { class: "ds-alert__icon", "aria-hidden": "true" },
})
export class TisAlertIcon {}

@Directive({
  selector: "[tisAlertContent]",
  standalone: true,
  host: { class: "ds-alert__content" },
})
export class TisAlertContent {}

@Directive({
  selector: "[tisAlertTitle]",
  standalone: true,
  host: { class: "ds-alert__title" },
})
export class TisAlertTitle {}

@Directive({
  selector: "[tisAlertDescription]",
  standalone: true,
  host: { class: "ds-alert__description" },
})
export class TisAlertDescription {}

@Directive({
  selector: "[tisAlertActions]",
  standalone: true,
  host: { class: "ds-alert__actions" },
})
export class TisAlertActions {}

@Directive({
  selector: "button[tisAlertClose]",
  standalone: true,
  host: { class: "ds-alert__close", type: "button" },
})
export class TisAlertClose {}

// registry/tis/alert.tsx
import * as React from "react"

import { cn } from "./tis-utils"

type AlertTone = "success" | "warning" | "error" | "info"
type AlertVariant = "solid" | "subtle"

type AlertProps = React.ComponentProps<"div"> & {
  tone?: AlertTone
  variant?: AlertVariant
}

function Alert({
  className,
  tone = "info",
  variant = "subtle",
  role = "alert",
  ...props
}: AlertProps) {
  return (
    <div
      data-slot="alert"
      data-tone={tone}
      data-variant={variant}
      role={role}
      className={cn(
        "ds-alert",
        `ds-alert--${tone}`,
        `ds-alert--${variant}`,
        className,
      )}
      {...props}
    />
  )
}

function withDsIconClass(children: React.ReactNode) {
  if (!React.isValidElement<{ className?: string }>(children)) return children
  return React.cloneElement(children, {
    className: cn("ds-icon", children.props.className),
  })
}

function AlertIcon({
  className,
  children,
  ...props
}: React.ComponentProps<"span">) {
  return (
    <span
      aria-hidden="true"
      data-slot="alert-icon"
      className={cn("ds-alert__icon", className)}
      {...props}
    >
      {withDsIconClass(children)}
    </span>
  )
}

function AlertContent({ className, ...props }: React.ComponentProps<"div">) {
  return (
    <div
      data-slot="alert-content"
      className={cn("ds-alert__content", className)}
      {...props}
    />
  )
}

function AlertTitle({ className, ...props }: React.ComponentProps<"p">) {
  return (
    <p
      data-slot="alert-title"
      className={cn("ds-alert__title", className)}
      {...props}
    />
  )
}

function AlertDescription({ className, ...props }: React.ComponentProps<"p">) {
  return (
    <p
      data-slot="alert-description"
      className={cn("ds-alert__description", className)}
      {...props}
    />
  )
}

function AlertActions({ className, ...props }: React.ComponentProps<"div">) {
  return (
    <div
      data-slot="alert-actions"
      className={cn("ds-alert__actions", className)}
      {...props}
    />
  )
}

type AlertCloseProps = React.ComponentProps<"button"> & {
  "aria-label": string
}

function AlertClose({
  className,
  children,
  type = "button",
  ...props
}: AlertCloseProps) {
  return (
    <button
      data-slot="alert-close"
      type={type}
      className={cn("ds-alert__close", className)}
      {...props}
    >
      {withDsIconClass(children)}
    </button>
  )
}

export {
  Alert,
  AlertActions,
  AlertClose,
  AlertContent,
  AlertDescription,
  AlertIcon,
  AlertTitle,
  type AlertProps,
  type AlertTone,
  type AlertVariant,
}
